TestNG Calculator tests
iraihnatovich/aqa_lessons pull request #1
Opened 2024-02-29 15:59 UTC by iraihnatovich

ДЗ по написанию методов div(int a, int b) and div(double a, double b)

У меня возникла проблема с BaseCalcTest.java:5 . При запуске группы через testGroupsCalculator.xml была ошибка NUllPointerException. Пробовала разные варианты (добавляла BeforeSuite группу, добавляла  классы Calculator, BaseCalcTest  под тэг <classes>) - получала java.lang.NullPointerException: Cannot invoke "Calculator.div(double, double)" because "this.calculator" is null
В итоге просто убрала инициализацию калькулятора из BeforeSuite - так тесты проходят

2024-03-03 18:41 UTC, wildpioneer requested changes

2024-03-03 18:41 UTC, wildpioneer commented on src/test/java/BaseCalcTest.java
> +    protected Calculator  calculator = new Calculator(); //вынесла сюда, ибо если иниц в @BeforeSuite ---> NUllPointerExc при запуске группы
@BeforeGroups - почему не использовала для групп?

2024-03-03 18:41 UTC, wildpioneer commented on src/test/java/data/CalculatorInfinityCaseDataProvider.java
> +//                {-651.65, 0, Double.NEGATIVE_INFINITY},
Закоментированные строки не оставляй в PR

2024-03-03 18:41 UTC, wildpioneer commented on src/test/java/CalculatorFunctionalTest.java
> +
Не нашел тесты:
1. description
2. @Parameters
3. retryAnalyzer

2024-03-04 14:04 UTC, iraihnatovich commented on src/test/java/BaseCalcTest.java
> +    protected Calculator  calculator = new Calculator(); //вынесла сюда, ибо если иниц в @BeforeSuite ---> NUllPointerExc при запуске группы
добавила  @BeforeGroups

2024-03-04 14:05 UTC, iraihnatovich commented on src/test/java/data/CalculatorInfinityCaseDataProvider.java
> +//                {-651.65, 0, Double.NEGATIVE_INFINITY},
исправлено

2024-03-04 14:08 UTC, iraihnatovich commented on src/test/java/CalculatorFunctionalTest.java
> +
добавила description, @Parameters и retryAnalyzer

2024-03-10 20:38 UTC, wildpioneer commented
Проверено

2024-03-10 20:38 UTC, closed without merging