Домашнее по wrappers
iraihnatovich/aqa_lessons pull request #10
Opened 2024-04-14 10:06 UTC by iraihnatovich

Домашнее сделано не полностью:

- Checkbox, RadioButton -- сделано полностью.
- wrapper Dropdown начала делать, но мне кажется, уже переусложнила -- необходимо каждый раз открывать дропдаун. Решила отправить как есть

2024-04-21 15:47 UTC, wildpioneer requested changes

2024-04-21 15:47 UTC, wildpioneer commented on src/test/java/wrappers/CheckBox.java
> +    public void setCheckBoxStatus (boolean status) {
Немного громоздкое название - ты уже в CheckBox
1. Я бы назвал setStatus
2. Я бы сделал два public метода set и remove - без параметров - а под капотом вызывал бы этот, которые бы перевел в private

2024-04-21 15:47 UTC, wildpioneer commented on src/test/java/wrappers/DropDown.java
> +    public void expandDropDown() {
Для чего этот метод public?

2024-04-27 09:10 UTC, iraihnatovich commented on src/test/java/wrappers/CheckBox.java
> +    public void setCheckBoxStatus (boolean status) {
исправлено

2024-04-27 09:11 UTC, iraihnatovich commented on src/test/java/wrappers/DropDown.java
> +    public void expandDropDown() {
исправила и переделала обертку DropDown

2024-04-29 09:36 UTC, wildpioneer commented
Проверено

2024-04-29 09:36 UTC, closed without merging