Selenium basic HomeWork
iraihnatovich/aqa_lessons pull request #2
Opened 2024-03-02 17:33 UTC by iraihnatovich

1. Доделанный тест из лекции -- src/test/java/SmokeTestSkf.java и src/test/java/SmokeTestSkfVar2.java .  Не смогла найти п11 (Поверхность тела: 1.58 кв м). Наверно, изменяли сайт.
2. Домашнее задание 1 из презентации --  WarmFloorCalculationTest.java
3. Домашнее задание 2 (*) из презентации --  LaminateTest.java . Сделала не до конца - проблемы:  
* не кликается radiobutton 
* не знаю пока, как переключится и закрыть поп-ап "Заявка на разработку онлайн-калькулятора"

2024-03-03 18:57 UTC, wildpioneer requested changes

2024-03-03 18:57 UTC, wildpioneer commented on src/test/java/LaminateTest.java
> +//       driver.switchTo().frame(); // не могу найти элем, на который переключится при появл поп-апа
Тут нужна пауза Thread.sleep - чтобы успело рассчитать

2024-03-03 18:57 UTC, wildpioneer commented on src/test/java/SmokeTestSkf.java
> +        WebElement mdrdNumberResult = driver.findElement(By.id("mdrd_res"));
Тут опять до проверки нужна небольшая пауза - Thread.sleep
С проверкой ты сложно придумала - посмотри на данный пример
System.out.println(driver.findElement(By.id("result")).getText().trim());

2024-03-05 11:38 UTC, iraihnatovich commented on src/test/java/LaminateTest.java
> +//       driver.switchTo().frame(); // не могу найти элем, на который переключится при появл поп-апа
добавила, рекламу закрываю руками

2024-03-05 11:40 UTC, iraihnatovich commented on src/test/java/SmokeTestSkf.java
> +        WebElement mdrdNumberResult = driver.findElement(By.id("mdrd_res"));
Thread.sleep добавила, проверку упростила

2024-03-10 20:39 UTC, closed without merging