Домашнее по Selenium WebDriver. Advanced
iraihnatovich/aqa_lessons pull request #4
Opened 2024-03-20 09:56 UTC by iraihnatovich

Выполнены все задания из https://docs.google.com/document/d/1LI99mPfiOnoxxnIZ7O98jk9MQh0il5n_CRIxKs7hs44/edit?usp=sharing

- core/WaitService.java:50 здесь не была уверена, какой эксепшен игнорировать при отсутствии файла в директории, поэтому написала RuntimeException.class

- AdvancedTest.java:87 решила удалять скачанный файл после теста

2024-03-25 12:19 UTC, wildpioneer requested changes

2024-03-25 12:19 UTC, wildpioneer commented on src/test/java/AdvancedTest.java
> +        WebElement uploadBtn = wait.waitForVisibility(By.cssSelector("#file-upload"));
Общая ошибка: Почему cssSelector а не ID?

2024-03-25 12:19 UTC, wildpioneer commented on src/test/java/AdvancedTest.java
> +        File folder = new File(getDownloadPath());
Не понимаю - а зачем эта двойная проверка?
Вначале ты проверяешь что файл скачался при помощи wait.fluentWaitForDownload(downloadFile.getText());
А затем опять проверяешь что он скачался на основании списка файлов

2024-03-25 12:19 UTC, wildpioneer commented on src/test/java/AdvancedTest.java
> +        new File(getDownloadPath(), downloadFile.getText()).deleteOnExit();
Эту строку вообще не понял

2024-03-26 14:55 UTC, iraihnatovich commented on src/test/java/AdvancedTest.java
> +        Actions action = new Actions(driver);
не совсем поняла, что именно исправить. Обычно делаю Reformat Code перед коммитом. В дальнейшем буду еще ориентироваться на Java Code Convention

2024-03-26 14:56 UTC, iraihnatovich commented on src/test/java/AdvancedTest.java
> +        File folder = new File(getDownloadPath());
Разобралась -- исправила

2024-03-26 14:58 UTC, iraihnatovich commented on src/test/java/AdvancedTest.java
> +        new File(getDownloadPath(), downloadFile.getText()).deleteOnExit();
в конце метода  downloadTest() удаляю скачанный файл, чтобы избежать такой ситуации (скрин)

![Screenshot 2024-03-25 at 16 28 03](https://github.com/iraihnatovich/aqa_lessons/assets/144908813/b8fbef18-bee8-4d09-a326-7a1fef554af6)

2024-04-07 17:50 UTC, wildpioneer commented on src/test/java/AdvancedTest.java
> +        Assert.assertEquals(alert.getText(), "You selected a context menu");
Перед Assert пустая строка

2024-04-07 17:52 UTC, wildpioneer commented
Проверено

2024-04-07 17:52 UTC, closed without merging