Домашеннее по PageObject
iraihnatovich/aqa_lessons pull request #6
Opened 2024-03-23 19:21 UTC by iraihnatovich

Сделала основное.

- Нет  метода getPageUrl() -- попробую доделать в воскресенье
- Страницы  Checkout* -- мне показалось, что именно для этого сценария можно не делать родительский абстрактный класс

2024-03-25 12:21 UTC, wildpioneer requested changes

2024-03-25 12:21 UTC, wildpioneer commented on src/test/java/tests/EndToEndTest.java
> +    public void e2eTest(@Optional("John") String firstName,
??? Ты используешь параметры при запуске?

2024-03-25 13:13 UTC, iraihnatovich commented on src/test/java/tests/EndToEndTest.java
> +    public void e2eTest(@Optional("John") String firstName,
добавила параметры

2024-04-07 17:52 UTC, wildpioneer commented
Проверено

2024-04-07 17:52 UTC, closed without merging